// Generated by gencpp from file rolf_pkg/ControlRequest.msg
// DO NOT EDIT!


#ifndef ROLF_PKG_MESSAGE_CONTROLREQUEST_H
#define ROLF_PKG_MESSAGE_CONTROLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rolf_pkg
{
template <class ContainerAllocator>
struct ControlRequest_
{
  typedef ControlRequest_<ContainerAllocator> Type;

  ControlRequest_()
    : header()
    , speed(0.0)
    , turn(0.0)  {
    }
  ControlRequest_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , speed(0.0)
    , turn(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _speed_type;
  _speed_type speed;

   typedef float _turn_type;
  _turn_type turn;





  typedef boost::shared_ptr< ::rolf_pkg::ControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rolf_pkg::ControlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ControlRequest_

typedef ::rolf_pkg::ControlRequest_<std::allocator<void> > ControlRequest;

typedef boost::shared_ptr< ::rolf_pkg::ControlRequest > ControlRequestPtr;
typedef boost::shared_ptr< ::rolf_pkg::ControlRequest const> ControlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rolf_pkg::ControlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rolf_pkg::ControlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rolf_pkg::ControlRequest_<ContainerAllocator1> & lhs, const ::rolf_pkg::ControlRequest_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.speed == rhs.speed &&
    lhs.turn == rhs.turn;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rolf_pkg::ControlRequest_<ContainerAllocator1> & lhs, const ::rolf_pkg::ControlRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rolf_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rolf_pkg::ControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rolf_pkg::ControlRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rolf_pkg::ControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rolf_pkg::ControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rolf_pkg::ControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rolf_pkg::ControlRequest_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rolf_pkg::ControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2efba620e13f7dc8f506729dd1f67c40";
  }

  static const char* value(const ::rolf_pkg::ControlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2efba620e13f7dc8ULL;
  static const uint64_t static_value2 = 0xf506729dd1f67c40ULL;
};

template<class ContainerAllocator>
struct DataType< ::rolf_pkg::ControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rolf_pkg/ControlRequest";
  }

  static const char* value(const ::rolf_pkg::ControlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rolf_pkg::ControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 speed\n"
"float32 turn\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::rolf_pkg::ControlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rolf_pkg::ControlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.speed);
      stream.next(m.turn);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rolf_pkg::ControlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rolf_pkg::ControlRequest_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "turn: ";
    Printer<float>::stream(s, indent + "  ", v.turn);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROLF_PKG_MESSAGE_CONTROLREQUEST_H
